In [ ]:
import numpy as np
import math  
from numpy import asarray


: 

In [261]:
points=[[3,5],[4,6],[2,8],[2,3],[1,4]]
points=np.asarray(points)
centers=[[2,4],[1,7]]
centers=np.asarray(centers)
q=2
lamda=1




In [290]:
def CalculateDistance(points,centers):

      return np.array([[ np.linalg.norm(i-j) for j in centers] for i in points])

  










In [263]:
distances=CalculateDistance(points,centers)
distances


array([[1.41421356, 2.82842712],
       [2.82842712, 3.16227766],
       [4.        , 1.41421356],
       [1.        , 4.12310563],
       [1.        , 3.        ]])

calculating eucledian distance with both clusters and iserting it to an array

In [264]:
distances_2=distances.tolist()


In [265]:
def CalculateMembership(distances,q):
  memberships=np.zeros(shape=(5,2))
  for k in range(len(distances_2)):
    for x in range(2):
        if(x==0):
         ans=(distances_2[k][0]/distances_2[k][0])**2+(distances_2[k][0]/distances_2[k][1])**2
         ans2=1/ans
         memberships[k][0]=ans2
        else:
         ans3=(distances_2[k][1]/distances_2[k][1])**2+(distances_2[k][1]/distances_2[k][0])**2
         ans4=1/ans3
         memberships[k][1]=ans4
  return memberships

calculating membership for each point 


In [266]:
rnk= CalculateMembership(distances,q)
rnk


array([[0.8       , 0.2       ],
       [0.55555556, 0.44444444],
       [0.11111111, 0.88888889],
       [0.94444444, 0.05555556],
       [0.9       , 0.1       ]])

In [267]:
def UpdateClusterMean(rnk,points,q):
    x1=0;
    y1=0;
    x2=0;
    y2=0;
    denominator1=0;
    denominator2=0;
    centers=np.zeros(shape=(2,2))

    for k in range(len(points)):
      x1=x1+((rnk[k][0])**2)*points[k][0]
      y1=y1+((rnk[k][0])**2)*points[k][1]
      x2=x2+((rnk[k][1])**2)*points[k][0]
      y2=y2+((rnk[k][1])**2)*points[k][1]
      denominator1=denominator1+(rnk[k][0])**2
      denominator2=denominator2+(rnk[k][1])**2
      centers[0][0]=x1/denominator1
      centers[0][1]=y1/denominator1
      centers[1][0]=x2/denominator2
      centers[1][1]=y2/denominator2
    return centers  
      


      
      







In [268]:
centers=UpdateClusterMean(rnk,points,q)
centers





array([[2.16796477, 4.15572554],
       [2.4084223 , 7.45183867]])

calculating new centers for each cluster

In [269]:
def CalculateObjectiveFunc(points,rnk,centers,q,lamda):
 final=0
 final2=0
 for k in range(len(points)):
  part1=((rnk[k][0])**2*(distances[k][0])**2)
  part2=((rnk[k][1])**2*(distances[k][1])**2)
  final=final+part1+part2
  part3=1*((rnk[k][0])+(rnk[k][1])-1)
  final2=final2+part3
  j=final+final2
 return j 




calculating objective function using the points, memberships , centers, q and lamda

In [270]:
J=CalculateObjectiveFunc(points,rnk,centers,q,lamda)
J

9.666666666666668

In [274]:
def ReachConvergence(points,rnk,centers,q,lamda):
 obj1=0
 distances=CalculateDistance(points,centers)
 rnk= CalculateMembership(distances,q)
 obj2=CalculateObjectiveFunc(points,rnk,centers,q,lamda)
 newcenters=UpdateClusterMean(rnk,points,q)
 #breakloop=False
 while(True):
   distances=CalculateDistance(points,centers)
   rnk=CalculateMembership(distances,q)
   centers=UpdateClusterMean(rnk,points,q)
   obj1=CalculateObjectiveFunc(points,rnk,centers,q,lamda)
   if(abs(obj1-obj2)>0.01):
     obj2=obj1
     newcenters=UpdateClusterMean(rnk,points,q)
   else: 
    break
 return rnk,newcenters   







In [275]:
convergence=ReachConvergence(points,rnk,centers,q,lamda)
convergence


(array([[0.8       , 0.2       ],
        [0.55555556, 0.44444444],
        [0.11111111, 0.88888889],
        [0.94444444, 0.05555556],
        [0.9       , 0.1       ]]), array([[2.16796477, 4.15572554],
        [2.4084223 , 7.45183867]]))